/**
 * Director agent-loop history utilities.
 *
 * The Director loop is now stateful within a single turn: it maintains a
 * `messages[]` array (system + initial user + alternating assistant
 * decisions and synthetic user "tool result" beats) and replays the whole
 * thing on every `directorClient.structured(...)` call. That gives the
 * Director real memory of its own prior decisions, which fixes runaway
 * `skill_check` chains, repeated tool errors, and the "looks like step 1
 * every step" behaviour that drove the old `MAX_SPEAKS_PER_ACTOR` quota.
 *
 * On long turns the message array would eventually overflow the model's
 * context window. We avoid that by collapsing the older middle of the
 * history into a single recap message whenever the previous Director
 * call's reported `prompt_tokens` exceeds `SUMMARY_TRIGGER_TOKENS`. The
 * recap is generated by a separate `summarizerClient` (defaults to the
 * Director's own client when no dedicated summarizer is configured).
 *
 * No client-side token estimation lives here — we use the API's own
 * `usage.prompt_tokens` from the previous response. If a provider omits
 * usage (older Ollama builds), the loop simply skips the budget check
 * for that step; if the LLM eventually hits its real context limit, the
 * next call surfaces an `LlmError` that already maps to a turn-error
 * event.
 */

/**
 * Collapse fires when the most recent Director call's reported
 * `prompt_tokens` exceeds this threshold. Tuned for ~8k-context local
 * models (qwen2.5:14b ships with an 8192-token window in its default
 * Ollama modelfile); adjust upward for cloud frontier models with
 * 200k+ windows if needed.
 */
export const SUMMARY_TRIGGER_TOKENS = 6000;

/**
 * After collapse, keep this many of the most recent assistant+tool-result
 * pairs verbatim. The Director needs the immediate tail at full fidelity
 * to make a coherent next-beat decision; older turns are fine in summary.
 */
export const SUMMARY_KEEP_LAST_PAIRS = 5;

/**
 * @typedef {import('../llm/client.d.ts').ChatMessage} ChatMessage
 * @typedef {import('../llm/client.d.ts').LlmClient} LlmClient
 */

/**
 * Render a synthetic user "tool result" message for the Director's
 * messages[] history. This mirrors the format of the deprecated
 * `ctx.last_beat` strings so the model already knows how to read them —
 * it's the same content, just delivered as a proper user turn instead
 * of a system-prompt block.
 *
 * @param {{ action: string }} decision   the Director's prior decision
 * @param {string} summary                the dispatcher's outcome string
 * @returns {string}
 */
export function formatToolResult(decision, summary) {
    const action = decision && typeof decision.action === 'string' ? decision.action : 'unknown';
    const body = String(summary || '').trim();
    if (!body) {
        return `Tool result for \`${action}\`: (no details)\nDecide the next beat.`;
    }
    return `Tool result for \`${action}\`:\n${body}\n\nDecide the next beat.`;
}

/**
 * Collapse the older middle of a Director history in place.
 *
 * Layout invariants the loop maintains:
 *   - `history[0]` is always the system prompt.
 *   - `history[1]` is always the initial user prompt (campaign + scene +
 *     transcript + player input).
 *   - From `history[2]` onward we have alternating
 *     `{role:'assistant', content:<decisionJson>}` and
 *     `{role:'user', content:<toolResult>}` messages.
 *
 * After this call the array still satisfies those invariants. We keep
 * the system + initial user, then a single synthetic
 * `{role:'user', content:<recap>}` summary message, then the last
 * `SUMMARY_KEEP_LAST_PAIRS * 2` messages verbatim. Everything in between
 * is summarised by the summariser.
 *
 * No-op if there is nothing in the middle to collapse (i.e. the history
 * is already shorter than `2 + SUMMARY_KEEP_LAST_PAIRS * 2`).
 *
 * @param {ChatMessage[]} history
 * @param {LlmClient} summarizerClient   the model that writes the recap
 * @param {AbortSignal} [signal]
 * @returns {Promise<{ collapsed: boolean, droppedCount: number, summary: string | null }>}
 */
export async function collapseOlderTurns(history, summarizerClient, signal) {
    if (!Array.isArray(history) || history.length < 2 + SUMMARY_KEEP_LAST_PAIRS * 2 + 2) {
        return { collapsed: false, droppedCount: 0, summary: null };
    }
    const fixedPrefixLen = 2;
    const tailLen = SUMMARY_KEEP_LAST_PAIRS * 2;
    const sliceStart = fixedPrefixLen;
    const sliceEnd = history.length - tailLen;
    if (sliceEnd <= sliceStart) {
        return { collapsed: false, droppedCount: 0, summary: null };
    }
    const dropped = history.slice(sliceStart, sliceEnd);
    if (!dropped.length) {
        return { collapsed: false, droppedCount: 0, summary: null };
    }

    const recap = await runSummarizer({ summarizerClient, dropped, signal });
    const summaryMessage = {
        role: /** @type {'user'} */ ('user'),
        content: `# Recap of earlier beats this turn\n${recap.trim()}\n\nThe most recent beats follow below at full fidelity.`,
    };

    history.splice(sliceStart, dropped.length, summaryMessage);
    return { collapsed: true, droppedCount: dropped.length, summary: recap };
}

/**
 * Run the summariser model on the dropped slice. Returns the raw recap
 * string; falls back to a best-effort textual concatenation if the LLM
 * call errors so the loop never crashes mid-turn over a summariser
 * failure (the recap is a quality optimisation, not a correctness
 * requirement).
 *
 * @param {{ summarizerClient: LlmClient, dropped: ChatMessage[], signal?: AbortSignal }} args
 * @returns {Promise<string>}
 */
async function runSummarizer({ summarizerClient, dropped, signal }) {
    const transcript = dropped.map(m => {
        const role = m.role === 'assistant' ? 'Director decision' : (m.role === 'user' ? 'Engine result' : m.role);
        return `[${role}]\n${m.content}`;
    }).join('\n\n');

    try {
        const recap = await summarizerClient.chat({
            system: summarizerSystemPrompt(),
            user: summarizerUserPrompt(transcript),
            signal,
        });
        const text = String(recap || '').trim();
        if (text) return text;
        return fallbackRecap(dropped);
    } catch (_err) {
        return fallbackRecap(dropped);
    }
}

/** @returns {string} */
function summarizerSystemPrompt() {
    return [
        'You are the Director\'s short-term memory summariser for a single TTRPG turn.',
        '',
        'You are given a chronological transcript of the Director\'s prior decisions in THIS turn and the engine\'s result for each. Produce a tight bullet-list recap so the Director, on its next call, can pick up where it left off without re-firing the same beats.',
        '',
        'Rules:',
        '- Output bullet points only. No prose paragraphs, no headings.',
        '- One bullet per Director beat, in order. Format: `- <action>(<key params>) → <outcome>`.',
        '  - Examples:',
        '    - `- speak: marle-the-investigator → Marle replied to the player about the dock thugs.`',
        '    - `- skill_check: actor=jack, voice=marle, intent="persuade Marle to give a name" → success (d20=14, total=18 vs DC 14); Marle reacted in her own voice.`',
        '    - `- spawn_character: from_source="new", name="Old Tom", brief="grizzled dock hand" → spawned as transient; not yet promoted.`',
        '    - `- search_library(query="bartender") → 1 match: \\`old_tom\\` — grizzled dock hand.`',
        '    - `- mutate_sheet: jack adjust_stat hp -4 → applied.`',
        '- Carry forward tool errors verbatim — they\'re critical recovery context.',
        '- Skip the rationale/intent text unless it\'s the only way to identify the beat.',
        '- Do not invent or speculate. If the engine result was empty, say so.',
        '- Maximum 25 bullets. Older beats may be merged into a single bullet if they cover redundant ground.',
    ].join('\n');
}

/** @param {string} transcript @returns {string} */
function summarizerUserPrompt(transcript) {
    return [
        '# Director transcript to summarise',
        transcript,
        '',
        'Produce the bullet-list recap now.',
    ].join('\n');
}

/**
 * Last-resort recap when the summariser model errors. Mirrors the shape
 * the summarised recap would have so the Director still gets something
 * actionable. Trims content aggressively to bound size.
 *
 * @param {ChatMessage[]} dropped
 * @returns {string}
 */
function fallbackRecap(dropped) {
    const lines = [];
    for (let i = 0; i < dropped.length; i += 2) {
        const decision = dropped[i];
        const result = dropped[i + 1];
        let action = '?';
        if (decision && decision.role === 'assistant') {
            try {
                const parsed = JSON.parse(decision.content);
                action = parsed.action || '?';
            } catch (_) {
                action = decision.content.slice(0, 60);
            }
        }
        const summary = result && result.role === 'user'
            ? result.content.replace(/^Tool result for `[^`]+`:\s*/, '').slice(0, 240)
            : '(no result)';
        lines.push(`- ${action} → ${summary.replace(/\s+/g, ' ').trim()}`);
    }
    return lines.join('\n') || '(no prior beats)';
}
