/**
 * Director agent-loop history utilities.
 *
 * The Director loop is stateful within a single turn: it maintains a
 * `messages[]` array (system + initial user + alternating assistant
 * `tool_call` selections and `role: 'tool'` engine results, anchored
 * to each other by `tool_call_id`) and replays the whole thing on
 * every `directorClient.tool(...)` call. That gives the Director real
 * memory of its own prior decisions and lets the chat template render
 * each engine result as a proper tool response — so the Director no
 * longer mistakes its own tool outputs for fresh player input the way
 * it did when results lived under `role: 'user'`.
 *
 * On long turns the message array would eventually overflow the model's
 * context window. We avoid that by collapsing the older middle of the
 * history into a single recap message whenever the previous Director
 * call's reported `prompt_tokens` exceeds `SUMMARY_TRIGGER_TOKENS`. The
 * recap is generated by a separate `summarizerClient` (defaults to the
 * Director's own client when no dedicated summarizer is configured).
 *
 * No client-side token estimation lives here — we use the API's own
 * `usage.prompt_tokens` from the previous response. If a provider omits
 * usage (older Ollama builds), the loop simply skips the budget check
 * for that step; if the LLM eventually hits its real context limit, the
 * next call surfaces an `LlmError` that already maps to a turn-error
 * event.
 */

/**
 * Collapse fires when the most recent Director call's reported
 * `prompt_tokens` exceeds this threshold. Tuned for ~8k-context local
 * models (qwen2.5:14b ships with an 8192-token window in its default
 * Ollama modelfile); adjust upward for cloud frontier models with
 * 200k+ windows if needed.
 */
export const SUMMARY_TRIGGER_TOKENS = 6000;

/**
 * After collapse, keep this many of the most recent assistant+tool-result
 * pairs verbatim. The Director needs the immediate tail at full fidelity
 * to make a coherent next-beat decision; older turns are fine in summary.
 */
export const SUMMARY_KEEP_LAST_PAIRS = 5;

/**
 * @typedef {import('../llm/client.d.ts').ChatMessage} ChatMessage
 * @typedef {import('../llm/client.d.ts').LlmClient} LlmClient
 */

/**
 * Render the `content` of the `role: 'tool'` result message that the
 * Director sees after dispatching one of its tool calls. The chat
 * template already frames this as a tool response anchored to the
 * matching `tool_call_id`, so we don't repeat the action name or beg
 * the model to "decide the next beat" — both of those used to leak
 * into the old `role: 'user'` stand-in and confuse small models into
 * treating tool outputs as a fresh user prompt.
 *
 * `decision` is accepted for API stability and to fall back to "(no
 * details for `<action>`)" when the dispatcher returned an empty
 * summary; nothing else of the decision shape is read.
 *
 * @param {{ action: string }} decision   the Director's prior decision
 * @param {string} summary                the dispatcher's outcome string
 * @returns {string}
 */
export function formatToolResult(decision, summary) {
    const body = String(summary || '').trim();
    if (body) return body;
    const action = decision && typeof decision.action === 'string' ? decision.action : 'unknown';
    return `(no details from \`${action}\`)`;
}

/**
 * Collapse the older middle of a Director history in place.
 *
 * Layout invariants the loop maintains:
 *   - `history[0]` is always the system prompt.
 *   - `history[1]` is always the initial user prompt (campaign + scene +
 *     transcript + player input).
 *   - From `history[2]` onward we have alternating
 *     `{role:'assistant', content:null, tool_calls:[{id, function:{name, arguments}}]}`
 *     and
 *     `{role:'tool', tool_call_id, content:<engine result>}`
 *     messages — one pair per Director step.
 *
 * After this call the array still satisfies those invariants. We keep
 * the system + initial user, then a single synthetic
 * `{role:'user', content:<recap>}` summary message, then the last
 * `SUMMARY_KEEP_LAST_PAIRS * 2` messages verbatim. Everything in between
 * is summarised by the summariser. The recap goes in as a `user` turn
 * (not `tool`) because there's no preceding `tool_calls` for it to
 * anchor onto.
 *
 * No-op if there is nothing in the middle to collapse (i.e. the history
 * is already shorter than `2 + SUMMARY_KEEP_LAST_PAIRS * 2`).
 *
 * @param {ChatMessage[]} history
 * @param {LlmClient} summarizerClient   the model that writes the recap
 * @param {AbortSignal} [signal]
 * @returns {Promise<{ collapsed: boolean, droppedCount: number, summary: string | null }>}
 */
export async function collapseOlderTurns(history, summarizerClient, signal) {
    if (!Array.isArray(history) || history.length < 2 + SUMMARY_KEEP_LAST_PAIRS * 2 + 2) {
        return { collapsed: false, droppedCount: 0, summary: null };
    }
    const fixedPrefixLen = 2;
    const tailLen = SUMMARY_KEEP_LAST_PAIRS * 2;
    const sliceStart = fixedPrefixLen;
    const sliceEnd = history.length - tailLen;
    if (sliceEnd <= sliceStart) {
        return { collapsed: false, droppedCount: 0, summary: null };
    }
    const dropped = history.slice(sliceStart, sliceEnd);
    if (!dropped.length) {
        return { collapsed: false, droppedCount: 0, summary: null };
    }

    const recap = await runSummarizer({ summarizerClient, dropped, signal });
    const summaryMessage = {
        role: /** @type {'user'} */ ('user'),
        content: `# Recap of earlier beats this turn\n${recap.trim()}\n\nThe most recent beats follow below at full fidelity.`,
    };

    history.splice(sliceStart, dropped.length, summaryMessage);
    return { collapsed: true, droppedCount: dropped.length, summary: recap };
}

/**
 * Run the summariser model on the dropped slice. Returns the raw recap
 * string; falls back to a best-effort textual concatenation if the LLM
 * call errors so the loop never crashes mid-turn over a summariser
 * failure (the recap is a quality optimisation, not a correctness
 * requirement).
 *
 * @param {{ summarizerClient: LlmClient, dropped: ChatMessage[], signal?: AbortSignal }} args
 * @returns {Promise<string>}
 */
async function runSummarizer({ summarizerClient, dropped, signal }) {
    const transcript = dropped.map(m => {
        if (m.role === 'assistant' && Array.isArray(m.tool_calls) && m.tool_calls.length) {
            const tc = m.tool_calls[0];
            return `[Director decision] ${tc?.function?.name || 'unknown'}(${tc?.function?.arguments || '{}'})`;
        }
        const role = m.role === 'assistant'
            ? 'Director decision'
            : (m.role === 'tool' ? 'Engine result' : (m.role === 'user' ? 'Engine result' : m.role));
        return `[${role}]\n${m.content || ''}`;
    }).join('\n\n');

    try {
        const recap = await summarizerClient.chat({
            system: summarizerSystemPrompt(),
            user: summarizerUserPrompt(transcript),
            signal,
            role: 'summarizer',
        });
        const text = String(recap || '').trim();
        if (text) return text;
        return fallbackRecap(dropped);
    } catch (_err) {
        return fallbackRecap(dropped);
    }
}

/** @returns {string} */
function summarizerSystemPrompt() {
    return [
        'You are the Director\'s short-term memory summariser for a single TTRPG turn.',
        '',
        'You are given a chronological transcript of the Director\'s prior decisions in THIS turn and the engine\'s result for each. Produce a tight bullet-list recap so the Director, on its next call, can pick up where it left off without re-firing the same beats.',
        '',
        'Rules:',
        '- Output bullet points only. No prose paragraphs, no headings.',
        '- One bullet per Director beat, in order. Format: `- <action>(<key params>) → <outcome>`.',
        '  - Examples:',
        '    - `- speak: marle-the-investigator → Marle replied to the player about the dock thugs.`',
        '    - `- skill_check: actor=jack, voice=marle, intent="persuade Marle to give a name" → success (d20=14, total=18 vs DC 14); Marle reacted in her own voice.`',
        '    - `- spawn_character: from_source="new", name="Old Tom", brief="grizzled dock hand" → spawned as transient; not yet promoted.`',
        '    - `- search_library(query="bartender") → 1 match: \\`old_tom\\` — grizzled dock hand.`',
        '    - `- mutate_sheet: jack adjust_stat hp -4 → applied.`',
        '- Carry forward tool errors verbatim — they\'re critical recovery context.',
        '- Skip the rationale/intent text unless it\'s the only way to identify the beat.',
        '- Do not invent or speculate. If the engine result was empty, say so.',
        '- Maximum 25 bullets. Older beats may be merged into a single bullet if they cover redundant ground.',
    ].join('\n');
}

/** @param {string} transcript @returns {string} */
function summarizerUserPrompt(transcript) {
    return [
        '# Director transcript to summarise',
        transcript,
        '',
        'Produce the bullet-list recap now.',
    ].join('\n');
}

/**
 * Last-resort recap when the summariser model errors. Mirrors the shape
 * the summarised recap would have so the Director still gets something
 * actionable. Trims content aggressively to bound size.
 *
 * @param {ChatMessage[]} dropped
 * @returns {string}
 */
function fallbackRecap(dropped) {
    const lines = [];
    for (let i = 0; i < dropped.length; i += 2) {
        const decision = dropped[i];
        const result = dropped[i + 1];
        let action = '?';
        if (decision && decision.role === 'assistant') {
            if (Array.isArray(decision.tool_calls) && decision.tool_calls.length) {
                action = decision.tool_calls[0]?.function?.name || '?';
            } else if (typeof decision.content === 'string' && decision.content.length) {
                // Legacy shape: assistant turns used to hold a JSON
                // string. Keep parsing it so an older history that
                // somehow flowed through here doesn't crash the recap.
                try {
                    const parsed = JSON.parse(decision.content);
                    action = parsed.action || '?';
                } catch (_) {
                    action = decision.content.slice(0, 60);
                }
            }
        }
        let summary = '(no result)';
        if (result && (result.role === 'tool' || result.role === 'user') && typeof result.content === 'string') {
            summary = result.content.replace(/^Tool result for `[^`]+`:\s*/, '').slice(0, 240);
        }
        lines.push(`- ${action} → ${summary.replace(/\s+/g, ' ').trim()}`);
    }
    return lines.join('\n') || '(no prior beats)';
}
