/**
 * Bounded Director loop for a single player turn.
 *
 * Dispatcher table:
 *   - `speak: narrator`       → Narrator client; emit a `message` (role:narrator).
 *   - `speak: <character_id>` → Actor client; emit a `message` (role:actor).
 *                               Per-actor scoped prompt — never sees other
 *                               actors' sheets. If the id is not in the
 *                               scene roster, the loop emits a recoverable
 *                               `tool_error` with closest matches and a
 *                               tool-result message in the Director's
 *                               history so it can recover (`search_library`,
 *                               `spawn_character`, or end the turn) on the
 *                               next step.
 *   - `skill_check`           → adjudicator decides skill/DC/severity, engine
 *                               rolls the d20, the model picked by the
 *                               Director's `voice` field writes the post-roll
 *                               beat. Emits ONE `roll` event combining the
 *                               card + narration so the frontend renders a
 *                               single styled bubble. `required:false` returns
 *                               to the loop without forcing a narrator beat.
 *   - `search_library`        → in-memory fuzzy search over off-stage
 *                               characters. No state mutation. Result is
 *                               returned to the Director via a tool-result
 *                               message in its history.
 *   - `spawn_character` (`from_source: 'library'`, `ref: <id>`) →
 *         add to `scene.participants`, emit a `state` (`change: 'spawn'`).
 *   - `spawn_character` (`from_source: 'new'`, `name`, `brief`) →
 *         create a transient (in-memory only) character; mirror into
 *         `ctx.actors`; emit a `state` (`change: 'spawn'`, `ephemeral: true`).
 *         Persistence is deferred until the character first speaks
 *         (promote-on-speak). If they never speak in this turn, they vanish.
 *   - `remove_character`      → remove from `scene.participants`, emit a
 *                               `state` (`change: 'remove'`).
 *   - `add_lore`              → write a generated world-lore entry.
 *   - `end_turn`              → emit `end_of_turn`.
 *   - everything else         → `error: unsupported_action`, force end.
 *
 * # Between-step communication: messages[] history
 *
 * The Director loop is a true agent loop within a single turn. Across
 * iterations the loop maintains a `directorHistory: ChatMessage[]` array
 * laid out as:
 *
 *   [0]   system prompt
 *   [1]   initial user prompt (campaign, scene, transcript, player input)
 *   [2]   assistant: decision1 JSON
 *   [3]   user:      tool result for decision1
 *   [4]   assistant: decision2 JSON
 *   [5]   user:      tool result for decision2
 *   ...
 *
 * On every step the loop replays the entire history into
 * `directorClient.structured({messages, ...})`. This gives the Director
 * real memory of its own prior decisions, which fixes runaway
 * `skill_check` chains, repeated tool errors, and the "looks like step 1
 * every step" behaviour that drove the old `MAX_SPEAKS_*` quotas.
 *
 * Each dispatcher returns `{ kind: 'continue', summary }` on success or
 * `{ kind: 'end' }` after emitting a terminal error. The loop calls
 * `formatToolResult(decision, summary)` to wrap the summary into a synthetic
 * user-role message and appends it to the history.
 *
 * On long turns the message array would eventually overflow the model's
 * context window. We avoid that by collapsing the older middle of the
 * history into a single recap message (via `collapseOlderTurns`) whenever
 * the previous Director call's reported `prompt_tokens` exceeds
 * `SUMMARY_TRIGGER_TOKENS`. The recap is generated by a separate
 * `summarizerClient` (defaults to the Director's own client when no
 * dedicated summarizer is configured).
 *
 * The loop emits TurnEvent objects via the supplied `emit(ev)` callback;
 * the HTTP handler is responsible for serialising those to NDJSON. This
 * separation keeps the loop testable from Node without spinning up Express.
 */

import { directorSystemPrompt, directorUserPrompt } from './prompts.js';
import { narratorSystemPrompt, narratorUserPrompt } from '../narrator/prompts.js';
import { actorSystemPrompt, actorUserPrompt, actorPostRollUserPrompt } from '../actors/prompts.js';
import { directorDecisionJsonSchema, validateDirectorDecision, SUPPORTED_ACTIONS } from './schemas.js';
import { LlmError } from '../llm/errors.js';
import * as skillEngine from '../skillcheck/engine.js';
import { narratorPostRollUserPrompt } from '../skillcheck/prompts.js';
import { formatSections } from '../rag/injection.js';
import { writeAddLore } from '../rag/writers/lore-add.js';
import { writeDirectorPacing } from '../rag/writers/director-pacing.js';
import { writeSheetMutationAudit } from '../rag/writers/sheet-mutation.js';
import { extractAndWriteOpinion } from '../rag/writers/opinion.js';
import { extractAndWriteNarratorContinuity } from '../rag/writers/narrator-continuity.js';
import { formatToolResult, collapseOlderTurns, SUMMARY_TRIGGER_TOKENS } from './history.js';

// A well-behaved turn looks like: speak(narrator) -> end_turn. We give the
// loop a small amount of slack so a Director that mis-classifies a beat can
// still recover, but we never want to run away into a 5+ beat monologue.
// Phase 5 raised the cap to absorb `spawn_character` + `speak: <actor>` in
// one turn; Phase 6 raises it again to absorb `skill_check` (one dispatch
// step that internally also consumes adjudicator + narrator calls) followed
// by an `end_turn`. With the messages[] history the Director can SEE its
// own prior beats, so the cap is now a budget (genuinely complex multi-NPC
// moments may chain a handful of beats), not a safety quota against
// runaway monologues — the agent loop self-regulates because each call
// carries the full history of what's already happened this turn.
const DEFAULT_MAX_STEPS = 8;

/**
 * @typedef {object} TurnEvent
 * @property {('status'|'message'|'state'|'roll'|'error'|'tool_error'|'end_of_turn'|'memory_write'|'sheet_mutated')} kind
 * @property {string} [phase]      for status: 'directing' | 'awaiting_actor' | 'rolling' | 'closing'
 * @property {string} [actor]      for message
 * @property {string} [name]       for message: display name
 * @property {string} [text]       for message
 * @property {string} [role]       for message: 'narrator' | 'actor' | 'system'
 * @property {string} [actor_id]   for message/roll: stable id of the speaking actor
 * @property {string} [actor_name] for roll
 * @property {string} [change]     for state: 'spawn' | 'remove'
 * @property {string} [character_id]    for state / sheet_mutated
 * @property {string} [character_name]  for state / sheet_mutated
 * @property {boolean} [ephemeral]      for state.spawn: character is held in-memory until first speak
 * @property {boolean} [promoted]       for state.spawn: a previously transient character was just persisted
 * @property {object} [card]       for roll: RollCard payload (skill, dc, breakdown, outcome, severity)
 * @property {string} [narration]  for roll: post-roll narrator prose
 * @property {string} [intent]     for roll: original director intent
 * @property {string} [code]       for error/tool_error
 * @property {string} [message]    for error/tool_error / status
 * @property {boolean} [retryable] for error
 * @property {string} [tool]       for tool_error: action name that errored (e.g. 'speak', 'spawn_character')
 * @property {string[]} [suggestions]   for tool_error: short human-readable recovery hints
 * @property {string} [reason]     for end_of_turn: 'director' | 'cap' | 'error' | 'aborted'
 * @property {string} [memory_kind]     for memory_write
 * @property {string} [record_id]       for memory_write
 * @property {string} [title]           for memory_write
 * @property {Array<{ op: string, ok: boolean, summary: string, error?: string }>} [ops_applied]  for sheet_mutated
 * @property {object} [sheet]      for sheet_mutated: the post-mutation sheet snapshot
 * @property {string} [audit_record_id]  for sheet_mutated: the director_memory record id of the audit row
 */

/**
 * @param {{
 *   ctx: import('./prompts.js').TurnContext,
 *   directorClient: import('../llm/client.d.ts').LlmClient,
 *   actorClient:    import('../llm/client.d.ts').LlmClient,
 *   adjudicatorClient?: import('../llm/client.d.ts').LlmClient,
 *   summarizerClient?: import('../llm/client.d.ts').LlmClient,
 *   ruleset?: import('../rulesets/schemas.d.ts').Ruleset | null,
 *   rng?: () => number,
 *   emit: (ev: TurnEvent) => Promise<void> | void,
 *   addParticipant?: (characterId: string) => Promise<import('../library/schemas.js').Character | null> | import('../library/schemas.js').Character | null,
 *   removeParticipant?: (characterId: string) => Promise<import('../library/schemas.js').Character | null> | import('../library/schemas.js').Character | null,
 *   findCharacter?: (characterId: string) => import('../library/schemas.js').Character | null,
 *   createCharacter?: (input: Partial<import('../library/schemas.js').Character> & { name: string }) => Promise<import('../library/schemas.js').Character> | import('../library/schemas.js').Character,
 *   mutateSheet?: (characterId: string, op: import('./schemas.js').SheetMutationOp) => Promise<import('../library/schemas.js').Character | null> | import('../library/schemas.js').Character | null,
 *   signal?: AbortSignal,
 *   maxSteps?: number,
 *   memoryService?: import('../rag/service.d.ts').MemoryService | null,
 *   sceneIndex?: number,
 * }} args
 */
export async function runTurn({
    ctx,
    directorClient,
    actorClient,
    adjudicatorClient,
    summarizerClient,
    ruleset,
    rng,
    emit,
    addParticipant,
    removeParticipant,
    findCharacter,
    createCharacter,
    mutateSheet,
    signal,
    maxSteps = DEFAULT_MAX_STEPS,
    memoryService = null,
    sceneIndex = 0,
}) {
    // Adjudicator defaults to the Director's own client — both are
    // structured-output-only and operate without RAG, per DESIGN.md's memory
    // injection rules.
    const adjudicator = adjudicatorClient || directorClient;
    // Summariser defaults to the Director's own client when no dedicated
    // role is configured. Summarisation runs at most once per long turn
    // so doubling up on the Director model is acceptable as a fallback.
    const summarizer = summarizerClient || directorClient;
    const cid = ctx.campaign?.id;
    let step = 0;
    let lastMemoryWriteId = 0;

    // M3: surface the sheet layout via ctx so prompt builders can render
    // category-aware YAML without each one re-importing the ruleset
    // loader. The layout is null when the campaign's ruleset shipped no
    // `sheet_layout.yaml` AND no universal overlay is on disk; the
    // renderer falls back to its flat KV dump in that case.
    if (ctx.sheet_layout === undefined) {
        ctx.sheet_layout = ruleset?.sheet_layout || null;
    }

    // Per-turn transient character store. The Director's `spawn_character`
    // with `from_source: 'new'` parks a new NPC here; we mirror them into
    // `ctx.actors` so subsequent steps can `speak` them. The character is
    // promoted to disk only when they actually speak (promote-on-speak), so
    // a typo'd spawn that's never followed up by a speak vanishes at end of
    // turn. Map<id, Character>.
    /** @type {Map<string, import('../library/schemas.js').Character>} */
    const transientCharacters = new Map();
    /** @type {Set<string>} */
    const promotedTransients = new Set();

    /** @param {string} id */
    const resolveCharacter = (id) => {
        if (!id) return null;
        if (transientCharacters.has(id)) return transientCharacters.get(id) || null;
        return findCharacter ? findCharacter(id) : null;
    };

    // Build the Director MEMORIES block ONCE before constructing the
    // initial user prompt. The query text is `pickQueryText(ctx)` which
    // returns the player's input (constant across the turn); re-fetching
    // every loop iteration would burn Qdrant calls without changing the
    // returned slice. Disk-canonical store; if Qdrant is down the
    // service returns empty hits and the loop continues.
    if (memoryService && cid) {
        try {
            const queryText = pickQueryText(ctx);
            const slice = await memoryService.for_director({ campaignId: cid, queryText });
            ctx.memories_block = formatSections([
                { kind: 'world_lore', hits: slice.world },
                { kind: 'director_memory', hits: slice.director, max: 4 },
            ]);
        } catch (err) {
            console.warn('[director-loop] memory injection failed', err?.message || err);
            ctx.memories_block = '';
        }
    }

    // Director agent-loop history. See the file header for the layout
    // invariants. The first two messages are pinned (system + initial
    // user); the loop appends an assistant decision + a user tool result
    // for every non-terminal beat. `collapseOlderTurns` may compact the
    // middle into a single recap when token budget is exceeded.
    /** @type {import('../llm/client.d.ts').ChatMessage[]} */
    const directorHistory = [
        { role: 'system', content: directorSystemPrompt(ctx) },
        { role: 'user',   content: directorUserPrompt(ctx) },
    ];
    let lastPromptTokens = 0;

    while (step < maxSteps) {
        if (signal?.aborted) {
            await emit({ kind: 'end_of_turn', reason: 'aborted' });
            return;
        }
        step++;

        await emit({ kind: 'status', phase: 'directing' });

        let decision;
        try {
            decision = await directorClient.structured({
                messages: directorHistory,
                schema: directorDecisionJsonSchema,
                schemaName: 'DirectorDecision',
                onUsage: (u) => { if (u && Number.isFinite(u.prompt_tokens)) lastPromptTokens = u.prompt_tokens; },
                signal,
            });
        } catch (err) {
            await emitError(emit, err, 'director');
            await emit({ kind: 'end_of_turn', reason: 'error' });
            return;
        }

        const validationErr = validateDirectorDecision(decision);
        if (validationErr) {
            await emit({ kind: 'error', code: 'invalid_decision', message: validationErr, retryable: false });
            await emit({ kind: 'end_of_turn', reason: 'error' });
            return;
        }

        if (!SUPPORTED_ACTIONS.has(decision.action)) {
            await emit({
                kind: 'error',
                code: 'unsupported_action',
                message: `Action "${decision.action}" is not yet implemented in this phase.`,
                retryable: false,
            });
            await emit({ kind: 'end_of_turn', reason: 'error' });
            return;
        }

        // Record the Director's decision in history before we dispatch.
        // The dispatcher's outcome will land as the matching tool-result
        // user message immediately after.
        directorHistory.push({ role: 'assistant', content: JSON.stringify(decision) });

        if (decision.action === 'end_turn') {
            // Phase 7: persist a director pacing note to director_memory if
            // the Director provided one via the optional `pacing_note` field.
            if (memoryService && cid && typeof decision.pacing_note === 'string') {
                writeDirectorPacing({
                    memoryService,
                    campaignId: cid,
                    sceneId: ctx.scene?.id || '',
                    sceneIndex,
                    pacingNote: decision.pacing_note,
                }).catch(() => {});
            }
            await emit({ kind: 'end_of_turn', reason: 'director' });
            return;
        }

        /** @type {{ kind: 'continue' | 'end', summary?: string }} */
        let outcome;

        if (decision.action === 'add_lore') {
            outcome = await dispatchAddLore({
                ctx, decision, emit, memoryService, cid, sceneIndex, step,
            });
        } else if (decision.action === 'speak') {
            outcome = await dispatchSpeak({
                ctx, decision, actorClient, emit, signal,
                resolveCharacter,
                transientCharacters,
                promotedTransients,
                createCharacter,
                addParticipant,
                memoryService, cid, sceneIndex,
            });
        } else if (decision.action === 'skill_check') {
            outcome = await dispatchSkillCheck({
                ctx,
                decision,
                ruleset: ruleset || null,
                adjudicatorClient: adjudicator,
                actorClient,
                rng,
                emit,
                signal,
                findCharacter: resolveCharacter,
                memoryService,
                cid,
                sceneIndex,
            });
        } else if (decision.action === 'search_library') {
            outcome = await dispatchSearchLibrary({ ctx, decision });
        } else if (decision.action === 'spawn_character') {
            outcome = await dispatchSpawn({
                ctx, decision, emit,
                addParticipant,
                resolveCharacter,
                transientCharacters,
            });
        } else if (decision.action === 'remove_character') {
            outcome = await dispatchRemove({
                ctx, decision, emit, removeParticipant,
                findCharacter: resolveCharacter,
                transientCharacters,
                promotedTransients,
            });
        } else if (decision.action === 'mutate_sheet') {
            outcome = await dispatchMutateSheet({
                ctx, decision, emit,
                findCharacter: resolveCharacter,
                mutateSheet,
                memoryService,
                cid,
                sceneIndex,
            });
        } else {
            // Unreachable: any newly supported action should have a branch above.
            await emit({ kind: 'error', code: 'internal', message: `Unhandled supported action ${decision.action}` });
            await emit({ kind: 'end_of_turn', reason: 'error' });
            return;
        }

        if (outcome.kind === 'end') {
            await emit({ kind: 'end_of_turn', reason: 'error' });
            return;
        }

        directorHistory.push({
            role: 'user',
            content: formatToolResult(decision, outcome.summary || ''),
        });

        // Collapse older turns if we've blown our token budget. The check
        // uses the API's own `prompt_tokens` from the previous response —
        // no client-side estimator. If the upstream omitted usage we
        // simply skip; if we eventually overflow, the next call will
        // surface an LlmError that maps to a turn-error event.
        if (lastPromptTokens > SUMMARY_TRIGGER_TOKENS) {
            try {
                const result = await collapseOlderTurns(directorHistory, summarizer, signal);
                if (result.collapsed) {
                    console.info(`[director-loop] history collapsed at ${lastPromptTokens} prompt tokens — replaced ${result.droppedCount} messages with one recap`);
                    // Reset our local counter so we don't re-collapse on
                    // every step until the next API response refreshes it.
                    lastPromptTokens = 0;
                }
            } catch (err) {
                console.warn('[director-loop] history collapse failed', err?.message || err);
            }
        }
    }

    void lastMemoryWriteId; // reserved for future debug hooks
    await emit({ kind: 'end_of_turn', reason: 'cap' });
}

/**
 * Pick a query string for retrieval. Prefer the player's latest input;
 * fall back to the recent transcript tail's last line if input is
 * silent.
 *
 * # Sheet-isolation invariant (M0)
 *
 * This reads ONLY from `ctx.user_input` and `ctx.recent_transcript`. It
 * MUST NOT touch `ctx.actors[].sheet` or any other character-sheet field.
 * Doing so would let sheet content (traits, pulse, relationships in the
 * post-overhaul layout) seed RAG retrieval and pull in unrelated memories
 * that match those sheet values. `tests/gm-core/rag-query-isolation.test.js`
 * pins this with poison-token assertions; do not regress it without
 * updating that test.
 *
 * Exported for the isolation test suite. Internal callers (the loop's RAG
 * sites) should not import it from outside this file — they already use
 * the in-module reference.
 *
 * @param {import('./prompts.js').TurnContext} ctx
 */
export function pickQueryText(ctx) {
    const ui = String(ctx.user_input || '').trim();
    if (ui) return ui;
    const tail = String(ctx.recent_transcript || '').trim();
    if (!tail) return '';
    const lines = tail.split('\n').filter(Boolean);
    return lines[lines.length - 1] || '';
}

/**
 * Dispatch an `add_lore` decision. Always returns a `continue` outcome —
 * lore writes never fail the turn. The summary string flows back into the
 * Director's history so it knows whether the lore was actually persisted
 * (when no memory service is wired the loop swallows it but still tells
 * the Director to move on).
 *
 * @param {{
 *   ctx: import('./prompts.js').TurnContext,
 *   decision: any,
 *   emit: (ev: TurnEvent) => Promise<void> | void,
 *   memoryService?: import('../rag/service.d.ts').MemoryService | null,
 *   cid?: string,
 *   sceneIndex?: number,
 *   step: number,
 * }} args
 * @returns {Promise<{ kind: 'continue', summary: string }>}
 */
async function dispatchAddLore({ ctx, decision, emit, memoryService, cid, sceneIndex, step }) {
    if (memoryService && cid) {
        const result = await writeAddLore({
            memoryService,
            campaignId: cid,
            sceneId: ctx.scene?.id || '',
            sceneIndex,
            directorStepIndex: step,
            decision,
        });
        if (result.wrote && result.id) {
            await emit({
                kind: 'memory_write',
                memory_kind: 'world_lore',
                record_id: result.id,
                title: decision.title,
            });
            appendToTail(ctx, 'System', `[lore added: ${decision.title}]`);
            return {
                kind: 'continue',
                summary: `add_lore committed: "${decision.title}". Decide the next beat (typically end_turn unless the player is still owed a response).`,
            };
        }
    }
    await emit({
        kind: 'status',
        phase: 'directing',
        message: 'add_lore: no memory service available; recording skipped.',
    });
    return {
        kind: 'continue',
        summary: 'add_lore: no memory service available; the lore was NOT recorded. Continue with the next beat.',
    };
}

/**
 * Dispatch a `speak` decision. Return values:
 *   - `{ kind: 'continue', summary }` — the actor / narrator was invoked
 *     (or a recoverable tool_error was emitted, e.g. unknown actor id).
 *     The summary captures what the Director needs to see in its history.
 *   - `{ kind: 'end' }` — an unrecoverable error was emitted; the loop
 *     should terminate.
 *
 * @param {{
 *   ctx: import('./prompts.js').TurnContext,
 *   decision: any,
 *   actorClient: import('../llm/client.d.ts').LlmClient,
 *   emit: (ev: TurnEvent) => Promise<void> | void,
 *   signal?: AbortSignal,
 *   resolveCharacter?: (characterId: string) => import('../library/schemas.js').Character | null,
 *   transientCharacters?: Map<string, import('../library/schemas.js').Character>,
 *   promotedTransients?: Set<string>,
 *   createCharacter?: (input: Partial<import('../library/schemas.js').Character> & { name: string }) => Promise<import('../library/schemas.js').Character> | import('../library/schemas.js').Character,
 *   addParticipant?: (characterId: string) => Promise<import('../library/schemas.js').Character | null> | import('../library/schemas.js').Character | null,
 * }} args
 * @returns {Promise<{ kind: 'continue', summary: string } | { kind: 'end' }>}
 */
async function dispatchSpeak({
    ctx, decision, actorClient, emit, signal,
    resolveCharacter, transientCharacters, promotedTransients,
    createCharacter, addParticipant,
    memoryService, cid, sceneIndex,
}) {
    await emit({ kind: 'status', phase: 'awaiting_actor' });

    const isNarrator = decision.actor === 'narrator';
    if (isNarrator) {
        // Narrator MEMORIES block: world_lore + own narrator_memory.
        const previousMemoriesBlock = ctx.memories_block;
        if (memoryService && cid) {
            try {
                const slice = await memoryService.for_narrator({
                    campaignId: cid,
                    queryText: decision.intent || pickQueryText(ctx),
                });
                ctx.memories_block = formatSections([
                    { kind: 'world_lore', hits: slice.world },
                    { kind: 'narrator_memory', hits: slice.narrator, max: 4 },
                ]);
            } catch (err) {
                console.warn('[loop.narrator] memory injection failed', err?.message || err);
                ctx.memories_block = '';
            }
        }
        let prose;
        try {
            prose = await actorClient.chat({
                system: narratorSystemPrompt(),
                user: narratorUserPrompt(ctx, decision.intent || ''),
                signal,
            });
        } catch (err) {
            ctx.memories_block = previousMemoriesBlock;
            await emitError(emit, err, 'narrator');
            return { kind: 'end' };
        }
        // Restore the Director-side memories block for subsequent steps.
        ctx.memories_block = previousMemoriesBlock;
        const text = (prose || '').trim();
        await emit({
            kind: 'message',
            actor: 'narrator',
            name: 'Narrator',
            role: 'narrator',
            text,
        });
        appendToTail(ctx, 'Narrator', text);

        if (memoryService && cid) {
            // Fire-and-forget continuity extractor. Its writes emit their own
            // memory_write events through the service path.
            extractAndWriteNarratorContinuity({
                memoryService,
                client: actorClient,
                campaignId: cid,
                sceneId: ctx.scene?.id || '',
                sceneName: ctx.scene?.name,
                location: ctx.scene?.location,
                sceneIndex,
                prose: text,
            }).then(result => {
                for (const rec of result.hits || []) {
                    emit({ kind: 'memory_write', memory_kind: 'narrator_memory', record_id: rec.id, title: rec.content }).catch(() => {});
                }
            }).catch(() => {});
        }
        return {
            kind: 'continue',
            summary: `Narrator just delivered the beat (intent: "${truncateForBeat(decision.intent)}"). The player has been responded to. Default to end_turn unless the player's input clearly demanded another beat.`,
        };
    }

    // Per-actor scoped speak. The Director picked an actor id; resolve the
    // character record via the loop's character lookup (which transparently
    // checks transient characters first). If the id is not in the scene
    // roster, surface a helpful tool_error and continue the loop so the
    // Director can recover via search_library / spawn_character / end_turn.
    const inScene = (ctx.actors || []).some(a => a.id === decision.actor);
    if (!inScene) {
        const suggestions = buildUnknownActorSuggestions(ctx, decision.actor);
        const message = `Actor "${decision.actor}" is not in the current scene roster.`;
        await emit({
            kind: 'tool_error',
            tool: 'speak',
            code: 'unknown_actor',
            message,
            suggestions,
        });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'speak', code: 'unknown_actor', message, suggestions }),
        };
    }
    const character = resolveCharacter ? resolveCharacter(decision.actor) : null;
    if (!character) {
        const suggestions = buildUnknownActorSuggestions(ctx, decision.actor);
        const message = `Could not load character "${decision.actor}".`;
        await emit({
            kind: 'tool_error',
            tool: 'speak',
            code: 'character_not_found',
            message,
            suggestions,
        });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'speak', code: 'character_not_found', message, suggestions }),
        };
    }
    if (character.is_player) {
        await emit({
            kind: 'tool_error',
            tool: 'speak',
            code: 'cannot_speak_for_player',
            message: 'The Director cannot speak for the player character. Pick the narrator or an NPC.',
        });
        return {
            kind: 'continue',
            summary: formatToolError({
                tool: 'speak',
                code: 'cannot_speak_for_player',
                message: `Tried to speak as the player character "${character.name}". The player drives the player. Pick narrator or an NPC; if no NPC fits, end_turn.`,
            }),
        };
    }

    // Per-actor MEMORIES block. Built per-call so the prior Director-side
    // block doesn't leak into the actor prompt.
    const previousMemoriesBlock = ctx.memories_block;
    if (memoryService && cid) {
        try {
            const slice = await memoryService.for_character({
                campaignId: cid,
                characterId: character.id,
                queryText: decision.intent || pickQueryText(ctx),
            });
            ctx.memories_block = formatSections([
                { kind: 'character_memory', label: character.id, hits: slice.character, max: 4 },
                { kind: 'world_lore', hits: slice.world, max: 5 },
                { kind: 'player_journal', hits: slice.player_journal, max: 1 },
            ]);
        } catch (err) {
            console.warn('[loop.actor] memory injection failed', err?.message || err);
            ctx.memories_block = '';
        }
    }

    let prose;
    try {
        prose = await actorClient.chat({
            system: actorSystemPrompt(ctx, character),
            user: actorUserPrompt(ctx, character, decision.intent || ''),
            signal,
        });
    } catch (err) {
        ctx.memories_block = previousMemoriesBlock;
        await emitError(emit, err, `actor:${character.id}`);
        return { kind: 'end' };
    }
    ctx.memories_block = previousMemoriesBlock;
    const text = (prose || '').trim();

    // Promote-on-speak: if the speaking character is a transient (created
    // via spawn_character: from_source: 'new'), persist them now and add to
    // scene.participants. This way a typo'd / abandoned spawn vanishes at
    // end of turn — only characters who actually said something become
    // permanent campaign records.
    let promotedNow = false;
    if (transientCharacters && transientCharacters.has(character.id) && !promotedTransients?.has(character.id)) {
        const promoted = await promoteTransient({
            transient: character,
            createCharacter,
            addParticipant,
        });
        if (promoted) {
            // Replace the transient with the persisted record across ctx.
            transientCharacters.set(promoted.id, promoted);
            promotedTransients?.add(promoted.id);
            const idx = (ctx.actors || []).findIndex(a => a.id === character.id);
            if (idx >= 0) {
                ctx.actors[idx] = {
                    id: promoted.id,
                    name: promoted.name,
                    is_player: promoted.is_player,
                    appearance: promoted.appearance,
                    personality: promoted.personality,
                    voice: promoted.voice,
                    background: promoted.background,
                };
            }
            promotedNow = true;
            await emit({
                kind: 'state',
                change: 'spawn',
                character_id: promoted.id,
                character_name: promoted.name,
                promoted: true,
            });
        }
    }

    await emit({
        kind: 'message',
        actor: character.id,
        actor_id: character.id,
        name: character.name,
        role: 'actor',
        text,
    });
    appendToTail(ctx, character.name, text);

    if (memoryService && cid && !promotedNow) {
        // Fire-and-forget opinion extractor. Bounded by the schema (max 2
        // memories) and the false-positive guard `is_significant`.
        // Skip on the first speak of a freshly promoted character: there's
        // no character_memory collection for them yet to populate, and the
        // RAG service may be initialising the new collection.
        extractAndWriteOpinion({
            memoryService,
            client: actorClient,
            campaignId: cid,
            character,
            sceneId: ctx.scene?.id || '',
            sceneIndex,
            messageIndex: Date.now(),
            lastMessage: text,
            transcriptTail: ctx.recent_transcript || '',
        }).then(result => {
            for (const rec of result.hits || []) {
                emit({ kind: 'memory_write', memory_kind: 'character_memory', record_id: rec.id, title: rec.content, character_id: character.id }).catch(() => {});
            }
        }).catch(() => {});
    }
    return {
        kind: 'continue',
        summary: `${character.name} (id: \`${character.id}\`) just spoke in response to the player's input${promotedNow ? ' (and was promoted from transient to a persistent campaign character)' : ''}. Default to end_turn unless the player's input clearly addressed multiple characters.`,
    };
}

/**
 * Promote a transient character to disk + scene participants. Returns the
 * persisted record on success, or null if persistence isn't wired (in
 * which case the transient stays transient and the speak still went out
 * with the in-memory identity — better than failing the beat).
 *
 * @param {{
 *   transient: import('../library/schemas.js').Character,
 *   createCharacter?: (input: Partial<import('../library/schemas.js').Character> & { name: string }) => Promise<import('../library/schemas.js').Character> | import('../library/schemas.js').Character,
 *   addParticipant?: (characterId: string) => Promise<import('../library/schemas.js').Character | null> | import('../library/schemas.js').Character | null,
 * }} args
 */
async function promoteTransient({ transient, createCharacter, addParticipant }) {
    if (!createCharacter) return null;
    try {
        const persisted = await createCharacter({
            name: transient.name,
            is_player: false,
            appearance: transient.appearance || '',
            personality: transient.personality || '',
            voice: transient.voice || '',
            background: transient.background || '',
            sheet: transient.sheet,
        });
        if (!persisted) return null;
        if (addParticipant) {
            try {
                await addParticipant(persisted.id);
            } catch (err) {
                console.warn('[loop.promote] addParticipant failed', err?.message || err);
            }
        }
        return persisted;
    } catch (err) {
        console.warn('[loop.promote] createCharacter failed', err?.message || err);
        return null;
    }
}

/** @param {string} s */
function truncateForBeat(s) {
    if (typeof s !== 'string') return '';
    return s.length > 120 ? `${s.slice(0, 117)}…` : s;
}

/**
 * Fuzzy match an unknown actor id/name against the current scene roster
 * and the off-stage library. Returns short hint strings the Director can
 * use to recover.
 *
 * @param {import('./prompts.js').TurnContext} ctx
 * @param {string} unknownId
 * @returns {string[]}
 */
function buildUnknownActorSuggestions(ctx, unknownId) {
    const needle = String(unknownId || '').toLowerCase();
    /** @type {string[]} */
    const out = [];
    const inSceneNonPc = (ctx.actors || []).filter(a => !a.is_player);
    const inSceneMatches = inSceneNonPc
        .filter(a => fuzzyMatch(a.id, needle) || fuzzyMatch(a.name, needle))
        .slice(0, 3);
    if (inSceneMatches.length) {
        out.push(`Closest in-scene actors: ${inSceneMatches.map(a => `\`${a.id}\` (${a.name})`).join(', ')}`);
    } else if (inSceneNonPc.length) {
        out.push(`In-scene NPCs you can speak as: ${inSceneNonPc.slice(0, 5).map(a => `\`${a.id}\` (${a.name})`).join(', ')}`);
    }
    const lib = ctx.library_characters || [];
    const libMatches = lib
        .filter(a => fuzzyMatch(a.id, needle) || fuzzyMatch(a.name, needle))
        .slice(0, 3);
    if (libMatches.length) {
        out.push(`Possible library matches (use \`spawn_character\` from_source: "library", ref: <id> first): ${libMatches.map(a => `\`${a.id}\` (${a.name})`).join(', ')}`);
    } else if (lib.length) {
        out.push('No close library matches. Try `search_library` with a query string, or `spawn_character` with from_source: "new", name, brief.');
    } else {
        out.push('No off-stage library characters. Use `spawn_character` with from_source: "new", name, brief — or end the turn.');
    }
    return out;
}

/**
 * Crude case-insensitive substring + token-overlap match. Good enough for
 * "bartender" matching "the_bartender" / "Old Bartender" / etc.
 *
 * @param {string} candidate
 * @param {string} needle    already lower-cased
 */
function fuzzyMatch(candidate, needle) {
    if (!candidate || !needle) return false;
    const c = String(candidate).toLowerCase();
    if (c.includes(needle) || needle.includes(c)) return true;
    const cTokens = c.split(/[\s_\-]+/).filter(Boolean);
    const nTokens = needle.split(/[\s_\-]+/).filter(Boolean);
    return cTokens.some(t => nTokens.some(n => t === n || t.includes(n) || n.includes(t)));
}

/**
 * Render a tool error for the Director's `# LAST BEAT` block.
 *
 * @param {{ tool: string, code: string, message: string, suggestions?: string[] }} err
 */
function formatToolError({ tool, code, message, suggestions }) {
    const lines = [
        `Tool error from \`${tool}\` (code: ${code}): ${message}`,
    ];
    if (suggestions && suggestions.length) {
        lines.push('Suggestions:');
        for (const s of suggestions) lines.push(`- ${s}`);
    }
    lines.push('Pick a different action — DO NOT repeat the same call. End the turn if no recovery makes sense.');
    return lines.join('\n');
}

/**
 * Dispatch a `skill_check` decision.
 *
 * 1. Resolve the actor (PC or in-scene NPC); reject anyone outside the roster.
 * 2. Emit a `rolling` status pill so the UI can show feedback.
 * 3. Call `engine.decide(...)` — strict, structured, no RAG.
 * 4. If the decision says no roll is needed, emit a status note and return
 *    control to the loop (Director gets to pick the next beat).
 * 5. Otherwise: roll the dice (pure), call the post-roll Narrator with the
 *    outcome, emit ONE combined `kind: 'roll'` event with both the card and
 *    the narration. Append a synthetic transcript-tail entry so subsequent
 *    Director steps in the same turn can reason about the result.
 *
 * @param {{
 *   ctx: import('./prompts.js').TurnContext,
 *   decision: any,
 *   ruleset: import('../rulesets/schemas.d.ts').Ruleset | null,
 *   adjudicatorClient: import('../llm/client.d.ts').LlmClient,
 *   actorClient: import('../llm/client.d.ts').LlmClient,
 *   rng?: () => number,
 *   emit: (ev: TurnEvent) => Promise<void> | void,
 *   signal?: AbortSignal,
 *   findCharacter?: (characterId: string) => import('../library/schemas.js').Character | null,
 * }} args
 */
async function dispatchSkillCheck({ ctx, decision, ruleset, adjudicatorClient, actorClient, rng, emit, signal, findCharacter, memoryService, cid, sceneIndex }) {
    if (!ruleset) {
        await emit({
            kind: 'error',
            code: 'no_ruleset',
            message: 'skill_check: no ruleset is loaded for this campaign.',
            retryable: false,
        });
        return { kind: 'end' };
    }

    const actorId = decision.actor;
    const inScene = (ctx.actors || []).some(a => a.id === actorId);
    if (!actorId || !inScene) {
        await emit({
            kind: 'error',
            code: 'unknown_actor',
            message: `skill_check: actor "${actorId}" is not in the current scene roster.`,
            retryable: false,
        });
        return { kind: 'end' };
    }
    const character = findCharacter ? findCharacter(actorId) : null;
    if (!character) {
        await emit({
            kind: 'error',
            code: 'character_not_found',
            message: `skill_check: could not load character "${actorId}".`,
            retryable: false,
        });
        return { kind: 'end' };
    }

    await emit({ kind: 'status', phase: 'rolling' });

    let skillDecision;
    try {
        skillDecision = await skillEngine.decide({
            ruleset,
            intent: String(decision.intent || ''),
            actorName: character.name,
            client: adjudicatorClient,
            signal,
        });
    } catch (err) {
        await emitError(emit, err, 'adjudicator');
        return { kind: 'end' };
    }

    if (!skillDecision.required) {
        // The adjudicator declined the roll. Surface a soft status so the
        // player can see something happened, then return to the loop without
        // forcing a narrator beat — the Director gets to pick the next move.
        await emit({
            kind: 'status',
            phase: 'directing',
            message: `No check needed: ${skillDecision.justification}`,
        });
        appendToTail(ctx, 'System', `[skill_check refused for ${character.name}: ${skillDecision.justification}]`);
        return {
            kind: 'continue',
            summary: `Adjudicator declined the skill_check for ${character.name} (intent: "${truncateForBeat(decision.intent)}"). Justification: ${skillDecision.justification}. Pick a non-skill_check beat or end_turn.`,
        };
    }

    /** @type {import('../skillcheck/schemas.d.ts').RollOutcome} */
    let outcome;
    try {
        outcome = skillEngine.roll({ ruleset, character, decision: skillDecision, rng });
    } catch (err) {
        await emit({
            kind: 'error',
            code: 'roll_failed',
            message: `skill_check roll: ${err?.message || err}`,
            retryable: false,
        });
        return { kind: 'end' };
    }

    // Build the chat-side card before we kick off the narrator so we can
    // pass the rendered details into the prose prompt.
    const card = skillEngine.renderRollCard({
        ruleset,
        character,
        decision: skillDecision,
        outcome,
        intent: String(decision.intent || ''),
    });

    // Decide who voices the post-roll consequence.
    //
    // The Director can pick `voice: '<character_id>'` for social checks
    // (persuade, intimidate, deceive) so the target NPC reacts in their
    // own first-person voice; otherwise we default to the World Narrator
    // (environmental / world checks: climb, perceive, sneak, lockpick).
    //
    // We degrade gracefully: a hallucinated voice id (not in scene, or
    // pointing at the actor performing the check, or pointing at the
    // player character) silently falls back to narrator voice. We never
    // tool-error out of a successful roll; the prose still has to land.
    const requestedVoice = typeof decision.voice === 'string' ? decision.voice.trim() : '';
    /** @type {{ kind: 'narrator' } | { kind: 'actor', character: import('../library/schemas.js').Character }} */
    let voiceChoice = { kind: 'narrator' };
    if (requestedVoice && requestedVoice !== 'narrator') {
        if (requestedVoice === actorId) {
            console.warn(`[loop.skillcheck] Director picked voice = self ("${requestedVoice}"); falling back to narrator voice.`);
        } else {
            const voiceTarget = (ctx.actors || []).find(a => a.id === requestedVoice);
            if (!voiceTarget) {
                console.warn(`[loop.skillcheck] Director picked voice = "${requestedVoice}" who is not in scene; falling back to narrator voice.`);
            } else if (voiceTarget.is_player) {
                console.warn(`[loop.skillcheck] Director picked voice = player character "${requestedVoice}"; falling back to narrator voice (player drives PC).`);
            } else {
                const voiceCharacter = findCharacter ? findCharacter(requestedVoice) : null;
                if (!voiceCharacter) {
                    console.warn(`[loop.skillcheck] Director picked voice = "${requestedVoice}" but the character record could not be loaded; falling back to narrator voice.`);
                } else {
                    voiceChoice = { kind: 'actor', character: voiceCharacter };
                }
            }
        }
    }

    // MEMORIES block for the post-roll beat. Per role:
    //   - narrator voice → world_lore + narrator_memory (same shape as
    //                      the `speak: narrator` branch).
    //   - actor voice    → that NPC's own character_memory + a slice of
    //                      world_lore + player_journal (same as the
    //                      `speak: <actor>` branch). Crucially: NEVER
    //                      another character's memory, even though the
    //                      reactor isn't the one rolling.
    const previousMemoriesBlock = ctx.memories_block;
    if (memoryService && cid) {
        try {
            if (voiceChoice.kind === 'actor') {
                const slice = await memoryService.for_character({
                    campaignId: cid,
                    characterId: voiceChoice.character.id,
                    queryText: String(decision.intent || character.name),
                });
                ctx.memories_block = formatSections([
                    { kind: 'character_memory', label: voiceChoice.character.id, hits: slice.character, max: 4 },
                    { kind: 'world_lore', hits: slice.world, max: 5 },
                    { kind: 'player_journal', hits: slice.player_journal, max: 1 },
                ]);
            } else {
                const slice = await memoryService.for_narrator({
                    campaignId: cid,
                    queryText: String(decision.intent || character.name),
                });
                ctx.memories_block = formatSections([
                    { kind: 'world_lore', hits: slice.world },
                    { kind: 'narrator_memory', hits: slice.narrator, max: 4 },
                ]);
            }
        } catch (err) {
            console.warn('[loop.skillcheck.post_roll] memory injection failed', err?.message || err);
            ctx.memories_block = '';
        }
    }

    let narration = '';
    let narrationSpeaker = 'Narrator';
    let narrationRole = 'narrator';
    let narrationActorId = null;
    try {
        const promptArgs = {
            actor_name: character.name,
            skill_name: card.skill_name,
            ability_name: card.ability_name,
            dc: card.dc,
            total: outcome.total,
            d20: outcome.d20,
            success: outcome.success,
            severity: skillDecision.failure_severity,
            crit: outcome.crit,
            intent: String(decision.intent || ''),
        };
        let system, user;
        if (voiceChoice.kind === 'actor') {
            system = actorSystemPrompt(ctx, voiceChoice.character);
            user = actorPostRollUserPrompt(ctx, voiceChoice.character, promptArgs);
            narrationSpeaker = voiceChoice.character.name;
            narrationRole = 'actor';
            narrationActorId = voiceChoice.character.id;
        } else {
            system = narratorSystemPrompt();
            user = narratorPostRollUserPrompt(ctx, promptArgs);
        }
        const prose = await actorClient.chat({ system, user, signal });
        narration = String(prose || '').trim();
    } catch (err) {
        ctx.memories_block = previousMemoriesBlock;
        await emitError(emit, err, voiceChoice.kind === 'actor' ? `actor:post_roll:${voiceChoice.character.id}` : 'narrator:post_roll');
        return { kind: 'end' };
    }
    ctx.memories_block = previousMemoriesBlock;

    await emit({
        kind: 'roll',
        actor_id: character.id,
        actor_name: character.name,
        intent: String(decision.intent || ''),
        card,
        narration,
        narration_speaker_id: narrationActorId,
        narration_speaker_name: narrationSpeaker,
        narration_speaker_role: narrationRole,
    });

    if (memoryService && cid) {
        if (narrationRole === 'actor' && narrationActorId) {
            // The reactor is now the speaker — extract opinion memory for
            // them, mirroring the `speak: <actor>` branch. Their reaction
            // prose is what the rest of the scene will remember.
            extractAndWriteOpinion({
                memoryService,
                client: actorClient,
                campaignId: cid,
                character: voiceChoice.kind === 'actor' ? voiceChoice.character : null,
                sceneId: ctx.scene?.id || '',
                sceneIndex,
                messageIndex: Date.now(),
                lastMessage: narration,
                transcriptTail: ctx.recent_transcript || '',
            }).then(result => {
                for (const rec of result.hits || []) {
                    emit({ kind: 'memory_write', memory_kind: 'character_memory', record_id: rec.id, title: rec.content, character_id: narrationActorId }).catch(() => {});
                }
            }).catch(() => {});
        } else {
            // Narrator continuity from the post-roll beat (existing path).
            extractAndWriteNarratorContinuity({
                memoryService,
                client: actorClient,
                campaignId: cid,
                sceneId: ctx.scene?.id || '',
                sceneName: ctx.scene?.name,
                location: ctx.scene?.location,
                sceneIndex,
                prose: narration,
            }).catch(() => {});
        }
    }

    // Synthesise a single recent-transcript line so subsequent Director steps
    // in the same turn can reason about what happened. We do NOT echo the
    // dice math — just the outcome and the prose, since that's what an
    // observer at the table would carry forward.
    const verdict = outcome.success ? 'succeeded' : 'failed';
    appendToTail(ctx, 'System', `[${character.name} ${verdict} their ${card.skill_name} check vs DC ${card.dc}]`);
    appendToTail(ctx, narrationSpeaker, narration);
    const voiceClause = narrationRole === 'actor'
        ? `${narrationSpeaker} reacted in their own voice`
        : 'The Narrator already described the consequence';
    return {
        kind: 'continue',
        summary: `${character.name} ${verdict} a ${card.skill_name} check vs DC ${card.dc} (d20=${outcome.d20}, total=${outcome.total}). ${voiceClause}. The roll has resolved and the consequence has been delivered. Default to end_turn — do NOT fire another skill_check for the same intent; the player's next turn drives what happens next.`,
    };
}

/**
 * Dispatch a `search_library` decision. No state mutation. Filters
 * `ctx.library_characters` (off-stage) by a free-text query against id,
 * name, and the short appearance/role blurb the HTTP wrapper attaches.
 * Result is returned as a tool-result summary so the Director can decide
 * what to do with the matches on its next step.
 *
 * @param {{ ctx: import('./prompts.js').TurnContext, decision: any }} args
 * @returns {Promise<{ kind: 'continue', summary: string }>}
 */
async function dispatchSearchLibrary({ ctx, decision }) {
    const query = String(decision.query || '').trim();
    if (!query) {
        return {
            kind: 'continue',
            summary: formatToolError({
                tool: 'search_library',
                code: 'empty_query',
                message: 'search_library was called with an empty query.',
                suggestions: ['Try `search_library` again with a non-empty query, or `spawn_character` with from_source: "new", name, brief.'],
            }),
        };
    }
    const lib = ctx.library_characters || [];
    if (!lib.length) {
        return {
            kind: 'continue',
            summary: `Tool result from \`search_library\` (query: "${query}"): the campaign library has no off-stage characters. Use \`spawn_character\` with from_source: "new", name: "...", brief: "..." to invent one — or end the turn.`,
        };
    }
    const needle = query.toLowerCase();
    const tokens = needle.split(/[\s_\-]+/).filter(Boolean);
    const scored = lib
        .map(c => {
            const hay = `${c.id || ''} ${c.name || ''} ${c.appearance || ''}`.toLowerCase();
            let score = 0;
            if (hay.includes(needle)) score += 5;
            for (const t of tokens) if (t && hay.includes(t)) score += 1;
            return { c, score };
        })
        .filter(x => x.score > 0)
        .sort((a, b) => b.score - a.score)
        .slice(0, 5)
        .map(x => x.c);
    if (!scored.length) {
        return {
            kind: 'continue',
            summary: `Tool result from \`search_library\` (query: "${query}"): no off-stage characters matched. Either invent one with \`spawn_character\` (from_source: "new", name, brief) or end the turn.`,
        };
    }
    const lines = [`Tool result from \`search_library\` (query: "${query}"): ${scored.length} match${scored.length === 1 ? '' : 'es'}:`];
    for (const c of scored) {
        const blurb = c.appearance ? ` — ${truncateForBeat(c.appearance)}` : '';
        lines.push(`- \`${c.id}\` — **${c.name}**${blurb}`);
    }
    lines.push('Use `spawn_character` with from_source: "library", ref: "<id>" to bring one of these characters on-stage, then `speak` them.');
    return { kind: 'continue', summary: lines.join('\n') };
}

/**
 * Dispatch `spawn_character`. Two paths:
 *
 *   - `from_source: 'library'` — bring an existing campaign character into
 *     the scene; persisted immediately via `addParticipant`.
 *   - `from_source: 'new'` — invent a transient character (in-memory only).
 *     They appear in `ctx.actors` so the Director can `speak` them next,
 *     but persistence is deferred to first speak (promote-on-speak in
 *     `dispatchSpeak`). If they never speak this turn, they vanish.
 *
 * @param {{
 *   ctx: import('./prompts.js').TurnContext,
 *   decision: any,
 *   emit: (ev: TurnEvent) => Promise<void> | void,
 *   addParticipant?: (characterId: string) => Promise<import('../library/schemas.js').Character | null> | import('../library/schemas.js').Character | null,
 *   resolveCharacter?: (characterId: string) => import('../library/schemas.js').Character | null,
 *   transientCharacters?: Map<string, import('../library/schemas.js').Character>,
 * }} args
 */
async function dispatchSpawn({ ctx, decision, emit, addParticipant, resolveCharacter, transientCharacters }) {
    if (decision.from_source === 'new') {
        return dispatchSpawnNew({ ctx, decision, emit, transientCharacters });
    }
    if (decision.from_source !== 'library') {
        const message = `spawn_character.from_source must be "library" or "new"; got "${decision.from_source}".`;
        const suggestions = ['Use from_source: "library" with a `ref` from the library list, or from_source: "new" with `name` and `brief`.'];
        await emit({
            kind: 'tool_error',
            tool: 'spawn_character',
            code: 'invalid_source',
            message,
        });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'spawn_character', code: 'invalid_source', message, suggestions }),
        };
    }
    const ref = decision.ref;
    if (!ref || typeof ref !== 'string') {
        const message = 'spawn_character from_source: "library" requires a `ref` (character id).';
        const suggestions = ['Use `search_library` first if you need to discover the right id.'];
        await emit({
            kind: 'tool_error',
            tool: 'spawn_character',
            code: 'missing_ref',
            message,
        });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'spawn_character', code: 'missing_ref', message, suggestions }),
        };
    }
    const character = resolveCharacter ? resolveCharacter(ref) : null;
    if (!character) {
        const message = `Character "${ref}" is not in this campaign.`;
        const suggestions = ['Try `search_library` with a query string, or `spawn_character` from_source: "new" with name and brief.'];
        await emit({
            kind: 'tool_error',
            tool: 'spawn_character',
            code: 'character_not_found',
            message,
            suggestions,
        });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'spawn_character', code: 'character_not_found', message, suggestions }),
        };
    }
    const already = (ctx.actors || []).some(a => a.id === ref);
    if (already) {
        // Idempotent: re-spawning a present participant is a no-op + status.
        await emit({
            kind: 'status',
            phase: 'directing',
            message: `${character.name} is already in the scene.`,
        });
        return {
            kind: 'continue',
            summary: `${character.name} (id: \`${character.id}\`) was already in the scene; no roster change. Continue.`,
        };
    }
    if (!addParticipant) {
        await emit({
            kind: 'error',
            code: 'no_participant_writer',
            message: 'spawn_character: scene participant writer not configured.',
            retryable: false,
        });
        return { kind: 'end' };
    }
    try {
        await addParticipant(character.id);
    } catch (err) {
        await emit({
            kind: 'error',
            code: 'spawn_failed',
            message: `Failed to add ${character.name} to the scene: ${err?.message || err}`,
            retryable: false,
        });
        return { kind: 'end' };
    }

    // Mirror the new participant into the working ctx so subsequent steps in
    // the same turn can reference them.
    ctx.actors = [...(ctx.actors || []), {
        id: character.id,
        name: character.name,
        is_player: character.is_player,
        appearance: character.appearance,
        personality: character.personality,
        voice: character.voice,
        background: character.background,
    }];

    await emit({
        kind: 'state',
        change: 'spawn',
        character_id: character.id,
        character_name: character.name,
    });
    return {
        kind: 'continue',
        summary: `${character.name} (id: \`${character.id}\`) entered the scene. Decide whether to \`speak\` as them next or hand the floor back via \`end_turn\`.`,
    };
}

/**
 * Spawn a brand new character into the scene as a TRANSIENT — held only in
 * the loop's `transientCharacters` map and mirrored into `ctx.actors`.
 * Never written to disk here; persistence is deferred until the character
 * first speaks (see `promoteTransient` in `dispatchSpeak`).
 *
 * @param {{
 *   ctx: import('./prompts.js').TurnContext,
 *   decision: any,
 *   emit: (ev: TurnEvent) => Promise<void> | void,
 *   transientCharacters?: Map<string, import('../library/schemas.js').Character>,
 * }} args
 */
async function dispatchSpawnNew({ ctx, decision, emit, transientCharacters }) {
    const name = String(decision.name || '').trim();
    const brief = String(decision.brief || '').trim();
    if (!name || !brief) {
        const message = 'spawn_character from_source: "new" requires both `name` and `brief`.';
        const suggestions = ['Retry with `name`: short display name, and `brief`: a one-sentence description (appearance, role, voice).'];
        await emit({
            kind: 'tool_error',
            tool: 'spawn_character',
            code: 'missing_fields',
            message,
        });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'spawn_character', code: 'missing_fields', message, suggestions }),
        };
    }
    if (!transientCharacters) {
        await emit({
            kind: 'error',
            code: 'no_transient_store',
            message: 'spawn_character (new): transient character store not configured.',
            retryable: false,
        });
        return { kind: 'end' };
    }
    const usedIds = new Set([
        ...(ctx.actors || []).map(a => a.id),
        ...(ctx.library_characters || []).map(c => c.id),
        ...transientCharacters.keys(),
    ]);
    const id = generateTransientId(name, usedIds);
    const now = new Date().toISOString();
    /** @type {import('../library/schemas.js').Character} */
    const transient = {
        id,
        campaign_id: ctx.campaign?.id || '',
        name,
        is_player: false,
        appearance: brief,
        personality: '',
        voice: '',
        background: '',
        sheet: { stats: {}, statuses: {}, items: [], skills: [], notes: '' },
        st_card_avatar: null,
        created_at: now,
        updated_at: now,
    };
    transientCharacters.set(id, transient);
    ctx.actors = [...(ctx.actors || []), {
        id,
        name,
        is_player: false,
        appearance: brief,
    }];
    await emit({
        kind: 'state',
        change: 'spawn',
        character_id: id,
        character_name: name,
        ephemeral: true,
    });
    return {
        kind: 'continue',
        summary: `Transient character "${name}" (id: \`${id}\`) spawned into the scene with brief: "${brief}". They will become a permanent campaign character only if you \`speak\` as them this turn. Decide whether to \`speak\` them next.`,
    };
}

/**
 * Generate a slug-style id from a name, suffixed if it collides.
 *
 * @param {string} name
 * @param {Set<string>} usedIds
 */
function generateTransientId(name, usedIds) {
    const base = String(name)
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '')
        .slice(0, 40) || 'npc';
    if (!usedIds.has(base)) return base;
    for (let i = 2; i < 1000; i++) {
        const candidate = `${base}_${i}`;
        if (!usedIds.has(candidate)) return candidate;
    }
    return `${base}_${Date.now()}`;
}

/**
 * @param {{
 *   ctx: import('./prompts.js').TurnContext,
 *   decision: any,
 *   emit: (ev: TurnEvent) => Promise<void> | void,
 *   removeParticipant?: (characterId: string) => Promise<import('../library/schemas.js').Character | null> | import('../library/schemas.js').Character | null,
 *   findCharacter?: (characterId: string) => import('../library/schemas.js').Character | null,
 *   transientCharacters?: Map<string, import('../library/schemas.js').Character>,
 *   promotedTransients?: Set<string>,
 * }} args
 */
async function dispatchRemove({ ctx, decision, emit, removeParticipant, findCharacter, transientCharacters, promotedTransients }) {
    const id = decision.character_id;
    if (!id || typeof id !== 'string') {
        const message = 'remove_character requires a `character_id`.';
        await emit({
            kind: 'tool_error',
            tool: 'remove_character',
            code: 'missing_character_id',
            message,
        });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'remove_character', code: 'missing_character_id', message }),
        };
    }
    const character = findCharacter ? findCharacter(id) : null;
    if (!character) {
        const message = `Character "${id}" is not in this campaign.`;
        await emit({
            kind: 'tool_error',
            tool: 'remove_character',
            code: 'character_not_found',
            message,
        });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'remove_character', code: 'character_not_found', message }),
        };
    }
    if (character.is_player) {
        const message = 'The player character cannot be removed from a scene.';
        await emit({
            kind: 'tool_error',
            tool: 'remove_character',
            code: 'cannot_remove_player',
            message,
        });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'remove_character', code: 'cannot_remove_player', message }),
        };
    }
    const present = (ctx.actors || []).some(a => a.id === id);
    if (!present) {
        await emit({
            kind: 'status',
            phase: 'directing',
            message: `${character.name} is not in the scene.`,
        });
        return {
            kind: 'continue',
            summary: `${character.name} (id: \`${character.id}\`) was not in the scene; nothing changed. Continue.`,
        };
    }

    // Transient (un-promoted) characters live only in the loop's transient
    // map. Removing them is a memory-only op — no participant writer call.
    const isTransient = transientCharacters && transientCharacters.has(character.id) && !promotedTransients?.has(character.id);
    if (isTransient) {
        transientCharacters.delete(character.id);
        ctx.actors = (ctx.actors || []).filter(a => a.id !== id);
        await emit({
            kind: 'state',
            change: 'remove',
            character_id: character.id,
            character_name: character.name,
        });
        return {
            kind: 'continue',
            summary: `${character.name} (transient) removed before they ever spoke; they're gone with no campaign record. Continue.`,
        };
    }

    if (!removeParticipant) {
        await emit({
            kind: 'error',
            code: 'no_participant_writer',
            message: 'remove_character: scene participant writer not configured.',
            retryable: false,
        });
        return { kind: 'end' };
    }
    try {
        await removeParticipant(character.id);
    } catch (err) {
        await emit({
            kind: 'error',
            code: 'remove_failed',
            message: `Failed to remove ${character.name} from the scene: ${err?.message || err}`,
            retryable: false,
        });
        return { kind: 'end' };
    }

    ctx.actors = (ctx.actors || []).filter(a => a.id !== id);

    await emit({
        kind: 'state',
        change: 'remove',
        character_id: character.id,
        character_name: character.name,
    });
    return {
        kind: 'continue',
        summary: `${character.name} (id: \`${character.id}\`) left the scene. Continue or end_turn.`,
    };
}

/**
 * Dispatch a `mutate_sheet` decision (M8).
 *
 * Sequence:
 *   1. Resolve the target character. The id MUST belong to a character
 *      currently in the scene roster (PC or NPC) — Director-driven sheet
 *      edits are scoped to the active scene so off-stage characters can't
 *      be silently changed.
 *   2. Apply each op in order via the supplied `mutateSheet` callback (a
 *      thin wrapper over `sheets/operations.js`). Op-level errors are
 *      collected and surfaced; an error in the middle of a multi-op
 *      decision does not roll back earlier ops (mutator writes are
 *      already on disk via `library/store.js`).
 *   3. Refresh `ctx.actors[i]` references and the resolved character so
 *      subsequent steps in this same turn (a follow-up `speak`, for
 *      instance) see the updated sheet via the per-actor renderer in
 *      `actors/prompts.js`.
 *   4. Emit a `sheet_mutated` event carrying the per-op results and the
 *      post-mutation sheet snapshot.
 *   5. Persist a one-line audit row into `director_memory__{cid}` via
 *      `writeSheetMutationAudit` so future Director steps can reason
 *      about state changes that weren't visible as speak/skill_check.
 *   6. Return a `continue` outcome whose summary describes what just
 *      changed, so the Director's next step sees the per-op results in
 *      its history as a tool-result message.
 *
 * @param {{
 *   ctx: import('./prompts.js').TurnContext,
 *   decision: any,
 *   emit: (ev: TurnEvent) => Promise<void> | void,
 *   findCharacter?: (characterId: string) => import('../library/schemas.js').Character | null,
 *   mutateSheet?: (characterId: string, op: import('./schemas.js').SheetMutationOp) => Promise<import('../library/schemas.js').Character | null> | import('../library/schemas.js').Character | null,
 *   memoryService?: import('../rag/service.d.ts').MemoryService | null,
 *   cid?: string,
 *   sceneIndex?: number,
 * }} args
 */
async function dispatchMutateSheet({ ctx, decision, emit, findCharacter, mutateSheet, memoryService, cid, sceneIndex }) {
    const targetId = String(decision.character_id || '').trim();
    if (!targetId) {
        const message = 'mutate_sheet.character_id is required.';
        await emit({ kind: 'tool_error', tool: 'mutate_sheet', code: 'missing_character_id', message });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'mutate_sheet', code: 'missing_character_id', message }),
        };
    }

    const inScene = (ctx.actors || []).some(a => a.id === targetId);
    if (!inScene) {
        const suggestions = buildUnknownActorSuggestions(ctx, targetId);
        const message = `mutate_sheet target "${targetId}" is not in the current scene roster.`;
        await emit({ kind: 'tool_error', tool: 'mutate_sheet', code: 'unknown_character', message, suggestions });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'mutate_sheet', code: 'unknown_character', message, suggestions }),
        };
    }

    const character = findCharacter ? findCharacter(targetId) : null;
    if (!character) {
        const message = `mutate_sheet could not load character "${targetId}".`;
        await emit({ kind: 'tool_error', tool: 'mutate_sheet', code: 'character_not_found', message });
        return {
            kind: 'continue',
            summary: formatToolError({ tool: 'mutate_sheet', code: 'character_not_found', message }),
        };
    }

    if (typeof mutateSheet !== 'function') {
        await emit({
            kind: 'error',
            code: 'no_sheet_writer',
            message: 'mutate_sheet: sheet writer not configured for this loop.',
            retryable: false,
        });
        return { kind: 'end' };
    }

    const ops = Array.isArray(decision.ops) ? decision.ops : [];
    /** @type {Array<{ op: string, ok: boolean, summary: string, error?: string }>} */
    const opsApplied = [];
    /** @type {import('../library/schemas.js').Character | null} */
    let updated = character;
    for (let i = 0; i < ops.length; i++) {
        const op = ops[i] || {};
        try {
            const result = await mutateSheet(targetId, op);
            if (result) {
                updated = result;
                opsApplied.push({ op: String(op.op || 'unknown'), ok: true, summary: summarizeSheetMutationOp(op) });
            } else {
                opsApplied.push({ op: String(op.op || 'unknown'), ok: false, summary: summarizeSheetMutationOp(op), error: 'mutator returned null' });
            }
        } catch (err) {
            opsApplied.push({
                op: String(op.op || 'unknown'),
                ok: false,
                summary: summarizeSheetMutationOp(op),
                error: err?.message || String(err),
            });
        }
    }

    // Mirror the updated character back into ctx.actors so subsequent
    // dispatch steps in this turn render the new sheet. ctx.actors[]
    // entries don't carry `sheet`, but the actor prompt builder pulls
    // the character via `findCharacter` (resolveCharacter) — that lookup
    // already returns the latest record because the endpoint's
    // `mutateSheet` callback is responsible for updating its own
    // by-id cache (see `endpoints/gm.js`). What we DO refresh here is
    // the cached display-name + identity blurb fields on ctx.actors so
    // the Director's user prompt stays consistent if a Director later
    // picks `speak` for the same actor on the next step.
    if (updated) {
        const idx = (ctx.actors || []).findIndex(a => a.id === updated.id);
        if (idx >= 0 && ctx.actors) {
            ctx.actors[idx] = {
                ...ctx.actors[idx],
                name: updated.name,
                appearance: updated.appearance,
                personality: updated.personality,
                voice: updated.voice,
                background: updated.background,
            };
        }
    }

    const okCount = opsApplied.filter(o => o.ok).length;
    const failCount = opsApplied.length - okCount;
    const headline = `Sheet for ${updated?.name || character.name} (id: \`${targetId}\`): ${okCount} op${okCount === 1 ? '' : 's'} applied${failCount ? `, ${failCount} failed` : ''}`;
    const summaryLines = opsApplied.map(o => o.ok ? `- ${o.summary}` : `- (failed) ${o.summary}: ${o.error || 'unknown error'}`);
    const auditSummary = `${headline}. ${opsApplied.map(o => o.summary).join('; ')}`;

    /** @type {string | undefined} */
    let auditRecordId;
    if (memoryService && cid && okCount > 0) {
        try {
            const result = await writeSheetMutationAudit({
                memoryService,
                campaignId: cid,
                sceneId: ctx.scene?.id || '',
                sceneIndex: typeof sceneIndex === 'number' ? sceneIndex : 0,
                characterId: targetId,
                summary: auditSummary,
            });
            if (result.wrote && result.id) {
                auditRecordId = result.id;
                await emit({
                    kind: 'memory_write',
                    memory_kind: 'director_memory',
                    record_id: result.id,
                    title: auditSummary,
                });
            }
        } catch (err) {
            console.warn('[loop.mutate_sheet] audit write failed', err?.message || err);
        }
    }

    await emit({
        kind: 'sheet_mutated',
        character_id: targetId,
        character_name: updated?.name || character.name,
        ops_applied: opsApplied,
        sheet: updated?.sheet || character.sheet,
        audit_record_id: auditRecordId,
    });

    return {
        kind: 'continue',
        summary: [
            headline + '.',
            ...summaryLines,
            failCount
                ? 'Some ops failed. Inspect the failures above before retrying. Do NOT repeat the failing call verbatim.'
                : 'The sheet is updated. Decide whether the player still needs a narrative beat (speak / narrator) or whether to end_turn.',
        ].join('\n'),
    };
}

/**
 * Render a per-op one-line summary used in both the `sheet_mutated`
 * event payload and the director_memory audit row. Pure (no I/O).
 *
 * @param {any} op
 * @returns {string}
 */
function summarizeSheetMutationOp(op) {
    if (!op || typeof op !== 'object') return 'unknown_op';
    switch (op.op) {
        case 'set_stat':     return `set_stat ${op.key} = ${formatScalarForBeat(op.value)}`;
        case 'adjust_stat': {
            const delta = Number(op.delta) || 0;
            const sign = delta >= 0 ? '+' : '';
            return `adjust_stat ${op.key} ${sign}${delta}`;
        }
        case 'clear_stat':   return `clear_stat ${op.key}`;
        case 'set_status':   return `set_status ${op.key} = ${formatScalarForBeat(op.value)}`;
        case 'clear_status': return `clear_status ${op.key}`;
        case 'add_item':     return `add_item "${truncateForBeat(String(op.name || ''))}"`;
        case 'update_item':  return `update_item ${op.item_id}${op.name ? ` (name="${truncateForBeat(String(op.name))}")` : ''}`;
        case 'remove_item':  return `remove_item ${op.item_id}`;
        default:             return `unknown_op:${String(op.op || '')}`;
    }
}

/** @param {unknown} v */
function formatScalarForBeat(v) {
    if (typeof v === 'number') return String(v);
    if (typeof v === 'string') return `"${truncateForBeat(v)}"`;
    return String(v);
}

/**
 * @param {(ev: TurnEvent) => Promise<void> | void} emit
 * @param {unknown} err
 * @param {string} stage
 */
async function emitError(emit, err, stage) {
    if (err instanceof LlmError) {
        await emit({ kind: 'error', code: err.code, message: `${stage}: ${err.message}`, retryable: err.retryable });
        return;
    }
    const message = (err && /** @type {Error} */(err).message) || String(err);
    await emit({ kind: 'error', code: 'unknown', message: `${stage}: ${message}`, retryable: false });
}

/**
 * @param {import('./prompts.js').TurnContext} ctx
 * @param {string} who
 * @param {string} text
 */
function appendToTail(ctx, who, text) {
    const tail = ctx.recent_transcript || '';
    const next = `${tail}${tail ? '\n' : ''}${who}: ${text}`;
    // Cap tail length to ~8000 chars (loose bound; the HTTP wrapper trims more
    // aggressively before passing the next director step).
    ctx.recent_transcript = next.length > 8000 ? next.slice(-8000) : next;
}
